### ISSUE TITLE
how to get the parameters of px4

### ISSUE THREAD

**Issue by suezere** [HKPolyU-UAV/airo_control_interface#1]
Hi, I want to know how to get the parameters of mpc_gazebo.yaml. For hover_thrust, I can get the UORB message but I don't know how to  identify the other parameters.

**Comment by RockyJBL** [comment]
The inner loop dynamics are assumed to be firsr-order dynamic systems. The time constants tau are derived by system identification. Basically, the quadrotor is commanded to go throught a series of maneuvers, and the inner loop references and responses are recorded. The time constants are calculated by linear regression. For more details please check system_identification.cpp or our paper at https://www.mdpi.com/2226-4310/9/8/460.

**Comment by suezere** [comment]
Thank you so much! I will check it.

**Comment by suezere** [comment]
Hello, I still have some questions. What exactly are these time constants tau identified by the system related to? Will the frequency of the callback function and the frequency of the timer affect it, or is it only related to the PID parameter inside the drone?
I use uXRCE-DDS for communication, but there is no /mavros/setpoint_raw/target_attitude topic in it, so I want to use mavros to systematically identify the parameters and communicate in uXRCE-DDS, is this feasible?

**Comment by RockyJBL** [comment]
The callback frequency will not affect the system id result since we used message filter to synchronize the attitude, attitude target, and the angular rate. It's value is related to the arm length, avionics, propellers, and PID parameters. You can check system_identification.cpp for details.
I'm not quite familiar with uXRCE-DDS but i think there should be topics publishing vehicle current attitude, target attitude, and current angular rates. Or, you can check the PX4 flightlogs if tf card to get those data and calculate the tau values.
